"""Policy evaluation and enforcement for encryption orchestration.

This module provides a policy engine that loads policy documents, validates
policy syntax, evaluates rules through `RuleEngine`, and returns normalized
policy decisions.
"""

from __future__ import annotations

import json
from collections import OrderedDict
from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from src.orchestration.encryption_orchestrator import EncryptionContext
from src.policy.rule_engine import RuleEngine


@dataclass(frozen=True)
class Policy:
    """Normalized policy definition used by orchestration."""

    name: str
    default_algorithm: str
    key_rotation_schedule: str
    compliance_tags: list[str] = field(default_factory=list)
    rules: list[dict[str, Any]] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class PolicyDecision:
    """Decision output generated by evaluating policy + context."""

    selected_algorithm: str
    key_rotation_schedule: str
    compliance_tags: list[str]


class PolicyEngine:
    """Load, validate, cache, and evaluate encryption policies."""

    def __init__(self, rule_engine: RuleEngine | None = None, cache_limit: int = 100) -> None:
        self._rule_engine = rule_engine or RuleEngine()
        self._cache_limit = max(1, int(cache_limit))
        self._cache: OrderedDict[Path, Policy] = OrderedDict()

    def load_policy(self, policy_path: Path) -> Policy:
        """Load a policy from disk with LRU caching.

        Args:
            policy_path: Filesystem path to JSON or YAML policy file.

        Returns:
            Parsed and validated `Policy` instance.
        """
        if not isinstance(policy_path, Path):
            raise TypeError("policy_path must be a pathlib.Path")

        normalized_path = policy_path.expanduser().resolve()
        cached = self._cache.get(normalized_path)
        if cached is not None:
            self._cache.move_to_end(normalized_path)
            return cached

        payload = self._read_policy_payload(normalized_path)
        self._validate_policy_syntax(payload)
        policy = self._to_policy(payload)

        self._cache[normalized_path] = policy
        self._cache.move_to_end(normalized_path)
        if len(self._cache) > self._cache_limit:
            self._cache.popitem(last=False)

        return policy

    def evaluate_policy(self, context: EncryptionContext, policy: Policy) -> PolicyDecision:
        """Evaluate policy against orchestration context.

        Args:
            context: Runtime encryption context.
            policy: Validated policy object.

        Returns:
            `PolicyDecision` containing selected algorithm, key rotation
            schedule, and compliance tags.
        """
        if not isinstance(policy, Policy):
            raise TypeError("policy must be a Policy instance")

        # Re-validate policy structure to guard against mutated objects.
        self._validate_policy_syntax(
            {
                "name": policy.name,
                "default_algorithm": policy.default_algorithm,
                "key_rotation_schedule": policy.key_rotation_schedule,
                "compliance_tags": policy.compliance_tags,
                "rules": policy.rules,
                "metadata": policy.metadata,
            }
        )

        decision_overrides = self._rule_engine.evaluate(context=context, policy=policy)
        if not isinstance(decision_overrides, Mapping):
            raise ValueError("RuleEngine must return a mapping of decision overrides")

        selected_algorithm = str(decision_overrides.get("selected_algorithm", policy.default_algorithm)).strip()
        key_rotation_schedule = str(
            decision_overrides.get("key_rotation_schedule", policy.key_rotation_schedule)
        ).strip()

        tags_override = decision_overrides.get("compliance_tags")
        merged_tags = self._merge_tags(policy.compliance_tags, tags_override)

        if not selected_algorithm:
            raise ValueError("selected_algorithm must be non-empty after evaluation")
        if not key_rotation_schedule:
            raise ValueError("key_rotation_schedule must be non-empty after evaluation")

        return PolicyDecision(
            selected_algorithm=selected_algorithm,
            key_rotation_schedule=key_rotation_schedule,
            compliance_tags=merged_tags,
        )

    @staticmethod
    def _read_policy_payload(path: Path) -> dict[str, Any]:
        if not path.exists():
            raise FileNotFoundError(f"policy file not found: {path}")

        raw_text = path.read_text(encoding="utf-8")
        suffix = path.suffix.lower()

        if suffix == ".json":
            payload = json.loads(raw_text)
        elif suffix in {".yaml", ".yml"}:
            payload = yaml.safe_load(raw_text)
        else:
            raise ValueError("unsupported policy format: use .json, .yaml, or .yml")

        if not isinstance(payload, dict):
            raise ValueError("policy root must be a mapping")
        return payload

    @classmethod
    def _validate_policy_syntax(cls, payload: Mapping[str, Any]) -> None:
        if not isinstance(payload, Mapping):
            raise ValueError("policy payload must be a mapping")

        cls._require_non_empty_string(payload.get("name"), "name")
        cls._require_non_empty_string(payload.get("default_algorithm"), "default_algorithm")
        cls._require_non_empty_string(payload.get("key_rotation_schedule"), "key_rotation_schedule")

        tags = payload.get("compliance_tags", [])
        if not isinstance(tags, list) or not all(isinstance(item, str) for item in tags):
            raise ValueError("compliance_tags must be a list of strings")

        rules = payload.get("rules", [])
        if not isinstance(rules, list):
            raise ValueError("rules must be a list")

        for index, rule in enumerate(rules):
            if not isinstance(rule, Mapping):
                raise ValueError(f"rules[{index}] must be a mapping")

            when = rule.get("when", {})
            decision = rule.get("decision", {})
            if not isinstance(when, Mapping):
                raise ValueError(f"rules[{index}].when must be a mapping")
            if not isinstance(decision, Mapping):
                raise ValueError(f"rules[{index}].decision must be a mapping")

            if "selected_algorithm" in decision:
                cls._require_non_empty_string(decision.get("selected_algorithm"), "selected_algorithm")
            if "key_rotation_schedule" in decision:
                cls._require_non_empty_string(decision.get("key_rotation_schedule"), "key_rotation_schedule")

            if "compliance_tags" in decision:
                d_tags = decision.get("compliance_tags")
                if not isinstance(d_tags, list) or not all(isinstance(item, str) for item in d_tags):
                    raise ValueError(f"rules[{index}].decision.compliance_tags must be a list of strings")

    @staticmethod
    def _to_policy(payload: Mapping[str, Any]) -> Policy:
        rules = payload.get("rules", [])
        metadata = payload.get("metadata", {})

        return Policy(
            name=str(payload["name"]).strip(),
            default_algorithm=str(payload["default_algorithm"]).strip(),
            key_rotation_schedule=str(payload["key_rotation_schedule"]).strip(),
            compliance_tags=[str(tag).strip() for tag in payload.get("compliance_tags", []) if str(tag).strip()],
            rules=[dict(rule) for rule in rules],
            metadata=dict(metadata) if isinstance(metadata, Mapping) else {},
        )

    @staticmethod
    def _merge_tags(base_tags: list[str], override_tags: Any) -> list[str]:
        merged = [tag.strip() for tag in base_tags if isinstance(tag, str) and tag.strip()]

        if override_tags is None:
            return merged
        if not isinstance(override_tags, list) or not all(isinstance(item, str) for item in override_tags):
            raise ValueError("decision.compliance_tags must be a list of strings")

        seen = {tag.lower() for tag in merged}
        for tag in override_tags:
            normalized = tag.strip()
            if normalized and normalized.lower() not in seen:
                merged.append(normalized)
                seen.add(normalized.lower())

        return merged

    @staticmethod
    def _require_non_empty_string(value: Any, field_name: str) -> None:
        if not isinstance(value, str) or not value.strip():
            raise ValueError(f"{field_name} must be a non-empty string")


__all__ = [
    "Policy",
    "PolicyDecision",
    "PolicyEngine",
]
