"""Educational entanglement-based encryption simulation.

This module demonstrates a simplified idea inspired by entanglement-assisted
key agreement. It is intentionally classical and pedagogical, not a secure
replacement for real quantum communication systems.

Theoretical basis (simplified):
- Multipartite GHZ states exhibit correlated measurement outcomes.
- If two parties measure corresponding qubits in aligned bases, they can derive
  correlated classical bits that may be post-processed into a shared key.
- In practice, real QKD/entanglement protocols require authenticated channels,
  reconciliation, privacy amplification, noise modeling, and rigorous security
  proofs.

Simulation limitations:
- Uses local statevector simulation (no physical quantum channel).
- Does not model adversarial interactions or full device noise.
- Correlation extraction is simplified and should only be used for learning.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from typing import Any

from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector


@dataclass(frozen=True)
class QuantumKey:
    """Container for simulated entanglement-derived key material."""

    n_pairs: int
    raw_bits: str
    ghz_circuits: tuple[QuantumCircuit, ...]


class EntanglementCryptoSimulator:
    """Simplified entanglement-based encryption simulator.

    Workflow:
    1. Generate GHZ states and sample correlated classical bits.
    2. Expand sampled bits into a byte keystream.
    3. Encrypt/decrypt with XOR against message bytes.

    This mirrors conceptually how correlated measurements can bootstrap
    classical cryptographic keys, but omits operational protocol details.
    """

    def __init__(self, ghz_size: int = 3) -> None:
        if ghz_size < 2:
            raise ValueError("ghz_size must be at least 2")
        self.ghz_size = ghz_size

    def generate_entangled_key_pairs(self, n_pairs: int) -> QuantumKey:
        """Generate entanglement-derived key pairs from GHZ states.

        Args:
            n_pairs: Number of GHZ states (key bits) to generate.

        Returns:
            QuantumKey containing raw correlated bits and underlying circuits.

        Notes:
        - Each GHZ state contributes one sampled classical bit.
        - The sampled bit is derived from measuring one qubit of the GHZ state;
          ideal GHZ correlations imply all qubits share that result in Z-basis.
        """
        if n_pairs <= 0:
            raise ValueError("n_pairs must be a positive integer")

        circuits: list[QuantumCircuit] = []
        bits: list[str] = []

        for _ in range(n_pairs):
            qc = self._create_ghz_circuit(self.ghz_size)
            circuits.append(qc)

            state = Statevector.from_instruction(qc)
            sample = next(iter(state.sample_counts(shots=1).keys()))
            # Qiskit bitstring ordering may be reversed by convention; for GHZ,
            # all bits are identical in ideal simulation, so picking one suffices.
            bit = sample[-1]
            bits.append(bit)

        return QuantumKey(n_pairs=n_pairs, raw_bits="".join(bits), ghz_circuits=tuple(circuits))

    def encrypt_with_entanglement(self, message: str, quantum_key: QuantumKey) -> dict[str, Any]:
        """Encrypt plaintext using a keystream derived from entangled key bits.

        Args:
            message: Plaintext string (UTF-8).
            quantum_key: QuantumKey generated by `generate_entangled_key_pairs`.

        Returns:
            Dictionary with hex ciphertext and metadata required for decryption.

        Raises:
            ValueError: If key material is insufficient or malformed.
        """
        if not isinstance(message, str):
            raise TypeError("message must be str")
        self._validate_quantum_key(quantum_key)

        plaintext = message.encode("utf-8")
        if not plaintext:
            return {
                "ciphertext_hex": "",
                "n_pairs": quantum_key.n_pairs,
                "raw_key_bits": quantum_key.raw_bits,
            }

        keystream = self._derive_keystream(quantum_key.raw_bits, len(plaintext))
        ciphertext = bytes(p ^ k for p, k in zip(plaintext, keystream))

        return {
            "ciphertext_hex": ciphertext.hex(),
            "n_pairs": quantum_key.n_pairs,
            "raw_key_bits": quantum_key.raw_bits,
        }

    def decrypt_with_entanglement(self, ciphertext_hex: str, quantum_key: QuantumKey) -> str:
        """Decrypt ciphertext using the same entanglement-derived key bits.

        Args:
            ciphertext_hex: Hex-encoded ciphertext from encryption output.
            quantum_key: Matching QuantumKey used during encryption.

        Returns:
            Decrypted UTF-8 plaintext string.
        """
        if not isinstance(ciphertext_hex, str):
            raise TypeError("ciphertext_hex must be str")
        self._validate_quantum_key(quantum_key)

        if ciphertext_hex == "":
            return ""

        try:
            ciphertext = bytes.fromhex(ciphertext_hex)
        except ValueError as exc:
            raise ValueError("ciphertext_hex is not valid hex") from exc

        keystream = self._derive_keystream(quantum_key.raw_bits, len(ciphertext))
        plaintext = bytes(c ^ k for c, k in zip(ciphertext, keystream))

        try:
            return plaintext.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise ValueError("decryption failed: key mismatch or corrupted ciphertext") from exc

    def _create_ghz_circuit(self, n_qubits: int) -> QuantumCircuit:
        qc = QuantumCircuit(n_qubits)
        qc.h(0)
        for i in range(1, n_qubits):
            qc.cx(0, i)
        return qc

    def _derive_keystream(self, raw_bits: str, n_bytes: int) -> bytes:
        if any(bit not in {"0", "1"} for bit in raw_bits):
            raise ValueError("raw_bits must contain only '0' and '1'")
        if len(raw_bits) == 0:
            raise ValueError("raw_bits must not be empty")

        seed_bytes = int(raw_bits, 2).to_bytes(max((len(raw_bits) + 7) // 8, 1), "big")
        stream = bytearray()
        counter = 0

        # Expand with SHA-256 in counter mode for deterministic simulation.
        while len(stream) < n_bytes:
            digest = hashlib.sha256(seed_bytes + counter.to_bytes(4, "big")).digest()
            stream.extend(digest)
            counter += 1

        return bytes(stream[:n_bytes])

    def _validate_quantum_key(self, quantum_key: QuantumKey) -> None:
        if not isinstance(quantum_key, QuantumKey):
            raise TypeError("quantum_key must be QuantumKey")
        if quantum_key.n_pairs <= 0:
            raise ValueError("quantum_key.n_pairs must be positive")
        if len(quantum_key.raw_bits) != quantum_key.n_pairs:
            raise ValueError("quantum_key.raw_bits length must match n_pairs")


__all__ = ["EntanglementCryptoSimulator", "QuantumKey"]
